### ISSUE TITLE
git_demographics-organizations-projects.json index name wrong?

### ISSUE THREAD

**Issue by acs** [grimoirelab/panels#2] opened 2016-09-14 05:27 UTC
The name used in this panel for the enriched index is git_enrich.

Is this correct? Should not be git?

**Comment by dicortazar** [comment] 2016-09-22 14:12
This should be git indeed. However I'm still in the process of migrating the panels to git...

I'll leave this open till those are migrated.

**Comment by acs** [comment] 2016-12-09 18:07
@dicortazar any update?

**Comment by dicortazar** [comment] 2016-12-20 15:42
not a bug anymore, closing the issue, thanks!

**Closed by dicortazar** 2016-12-20 15:42 UTC
